version: '3'

services:
  daemon:
    image: funkypenguin/turtlecoind
    volumes:
<<<<<<< HEAD
      - /var/data/turtle-pool/daemon/1:/var/lib/turtlecoind/
=======
      - data/daemon:/var/lib/turtlecoind/
>>>>>>> cab114d45e3b38a1018c35c4feacda0f6e52b76b
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 11897:11897
      
  daemon-failsafe:
    image: funkypenguin/turtlecoind
    volumes:
<<<<<<< HEAD
      - /var/data/turtle-pool/daemon/failsafe:/var/lib/turtlecoind/
=======
      - data/failsafe:/var/lib/turtlecoind/
>>>>>>> cab114d45e3b38a1018c35c4feacda0f6e52b76b
      - /etc/localtime:/etc/localtime:ro

  pool-pool:
    image: funkypenguin/turtle-pool
    volumes:
      - turtle-pool:/config:ro
      - data/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3333:3333
      - 5555:5555
      - 7777:7777
      - 8117:8117
    entrypoint: |
<<<<<<< HEAD
      node init.js -config=/config/config.json
=======
      node init.js -module=pool -config=/config/config.json

>>>>>>> cab114d45e3b38a1018c35c4feacda0f6e52b76b

  
  wallet:
    image: funkypenguin/turtlecoind
    volumes:
      - /var/data/turtle-pool/wallet/config:/config:ro
      - /var/data/turtle-pool/wallet/container:/container
      - /var/data/turtle-pool/wallet/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      walletd --config /config/wallet.conf | tee /logs/walletd.log

  redis:
    volumes:
      - /var/data/turtle-pool/redis/config:/config:ro
      - /var/data/turtle-pool/redis/data:/data
      - /var/data/turtle-pool/redis/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    image: redis
    entrypoint: |
      redis-server /config/redis.conf

  nginx:
    volumes:
      - /var/data/turtle-pool/nginx/website:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    image: nginx

