version: '3'

services:
  daemon:
    image: turtlecoin
    volumes:
      - /var/data/daemon/1:/var/lib/turtlecoind/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 11897:11897
      - 11898:11898
      
  daemon-failsafe:
    image: turtlecoin
    volumes:
      - /var/data/daemon/failsafe:/var/lib/turtlecoind/
      - /etc/localtime:/etc/localtime:ro

  pool-pool:
    image: turtle-pool
    volumes:
      - ./config:/config:ro
      - /var/data/pool-pool/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3333:3333
      - 5555:5555
      - 7777:7777
      - 8117:8117
    depends_on:
      - wallet
      - reids
      - daemon
    entrypoint: |
      node init.js -config=/config/config.json

  
  wallet:
    image: turtlecoin
    volumes:
      - ./config:/config:ro
      - /var/data/wallet/container:/container
      - /var/data/wallet/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - daemon
    entrypoint: |
      walletd --config /config/wallet.conf | tee /logs/walletd.log

  redis:
    volumes:
      - ./config:/config:ro
      - /var/data/redis/data:/data
      - /var/data/redis/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    image: redis:4.0.10
    entrypoint: |
      redis-server /config/redis.conf

  nginx:
    volumes:
      - /var/data/nginx/website:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    image: nginx:1.15.2
    ports:
      - 80:80

