version: '3'

services:
  daemon:
    image: funkypenguin/turtlecoind
    volumes:
      - /var/data/turtle-pool/daemon/1:/var/lib/turtlecoind/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 11897:11897
    

  daemon-failsafe:
    image: funkypenguin/turtlecoind
    volumes:
      - /var/data/turtle-pool/daemon/failsafe:/var/lib/turtlecoind/
      - /etc/localtime:/etc/localtime:ro

  pool-pool:
    image: funkypenguin/turtle-pool
    volumes:
      - /var/data/turtle-pool/pool/config:/config:ro
      - /var/data/turtle-pool/pool/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3333:3333
      - 5555:5555
      - 7777:7777
      - 8117:8117
    entrypoint: |
      node init.js -config=/config/config.json

  
  wallet:
    image: funkypenguin/turtlecoind
    volumes:
      - /var/data/turtle-pool/wallet/config:/config:ro
      - /var/data/turtle-pool/wallet/container:/container
      - /var/data/turtle-pool/wallet/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      walletd --config /config/wallet.conf | tee /logs/walletd.log

  redis:
    volumes:
      - /var/data/turtle-pool/redis/config:/config:ro
      - /var/data/turtle-pool/redis/data:/data
      - /var/data/turtle-pool/redis/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    image: redis
    entrypoint: |
      redis-server /config/redis.conf

  nginx:
    volumes:
      - /var/data/turtle-pool/nginx/website:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    image: nginx

